name: ojt-backend-prod

services:
  postgres:
    image: postgis/postgis:18-3.6
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
    ports:
      - "${POSTGRESQL_EXTERNAL_PORT}:5432"
    volumes:
      - postgres-prod-data:/var/lib/postgresql
    networks:
      - backend

  redis:
    image: redis:8.4.0
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - redis-prod-data:/data
    networks:
      - backend

  spring-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: spring-app
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    ports:
      - "${SPRING_EXTERNAL_PORT}:8080"
    environment:
      SERVER_PORT: 8080
      # ===== PostgreSQL =====
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRESQL_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRESQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRESQL_PASSWORD}

      # ===== Redis =====
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}

      # ===== JVM =====
      JAVA_OPTS: -Xms256m -Xmx512m
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-prod-data:
  redis-prod-data:
