name: ojt-backend-infra

services:
  postgres:
    image: postgis/postgis:18-3.6
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
    ports:
      - "${POSTGRESQL_EXTERNAL_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:8.4.0
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
