name: ojt-backend

services:
  ojt-backend:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    container_name: ojt-backend
    restart: always
    env_file:
      - ../../.env
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST_PROD}
      - POSTGRESQL_EXTERNAL_PORT=${POSTGRESQL_EXTERNAL_PORT_PROD}
      - REDIS_HOST=${REDIS_HOST_PROD}
      - REDIS_EXTERNAL_PORT=${REDIS_EXTERNAL_PORT_PROD}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgis/postgis:18-3.6
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
    ports:
      - "${POSTGRESQL_EXTERNAL_PORT_PROD}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:8.4.0
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "${REDIS_EXTERNAL_PORT_PROD}:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
